executable            = condor.sh
requirements          = (OpSysAndVer =?= "CentOS7")
error                 = logs/$(ClusterId).$(ProcId).err
output                = logs/$(ClusterId).$(ProcId).out
+JobBatchName         = "$label"
+JobFlavour           = "workday"
should_transfer_files = YES
transfer_input_files  = xy_distributions_cfg.py,direct_simu_reco_cff.py,tarball.tar.gz
CMSSW                 = $cmssw
arguments             = $(CMSSW) xy_distributions_cfg.py
queue
